//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDC_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class user
    {
        [Key]
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<int> work_number { get; set; }
        public int mobile_number { get; set; }
        public virtual Gender userGender { set; get; }
        public Nullable<int> id_number { get; set; }
        public string password { get; set; }
        public virtual ICollection<Booking> bookings { get; set; }
        public virtual ICollection<BookingUsers> booking_assigned_user { get; set; }
        public virtual Department department { get; set; }
        public virtual Organization organization { get; set; }
        public virtual Position position { get; set; }
        [ForeignKey("position")]
        public int position_id { get; set; }
        public virtual ICollection<user_group> user_group { get; set; }
    }
}
