//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDC_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @object()
        {
            this.booking_object = new HashSet<booking_object>();
            this.object_property = new HashSet<object_property>();
        }
    
        public int object_id { get; set; }
        public string object_name { get; set; }
        public Nullable<int> object_capacity { get; set; }
        public byte[] object_image { get; set; }
        public string object_description { get; set; }
        public string object_brand { get; set; }
        public string object_location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_object> booking_object { get; set; }
        public virtual object_type object_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<object_property> object_property { get; set; }
        public virtual template template { get; set; }
    }
}
