//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDC_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_object
    {
        public int booking_object_id { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual @object @object { get; set; }
    }
}
