//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDC_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_operation
    {
        public int group_operation_id { get; set; }
    
        public virtual group group { get; set; }
        public virtual operation operation { get; set; }
    }
}
