//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDC_WebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSDCEntities : DbContext
    {
        public SSDCEntities()
            : base("name=SSDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<additional_service> additional_service { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<booking_assigned_user> booking_assigned_user { get; set; }
        public virtual DbSet<booking_object> booking_object { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<field> fields { get; set; }
        public virtual DbSet<field_option> field_option { get; set; }
        public virtual DbSet<field_result> field_result { get; set; }
        public virtual DbSet<form> forms { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<group_operation> group_operation { get; set; }
        public virtual DbSet<@object> objects { get; set; }
        public virtual DbSet<object_property> object_property { get; set; }
        public virtual DbSet<object_type> object_type { get; set; }
        public virtual DbSet<operation> operations { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<organization_type> organization_type { get; set; }
        public virtual DbSet<participant_level> participant_level { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<property_type> property_type { get; set; }
        public virtual DbSet<service_cost> service_cost { get; set; }
        public virtual DbSet<template> templates { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_group> user_group { get; set; }
    }
}
